using UnityEngine;

public enum StatType
{
    Speed,
    MaxHeath, 
    JumpHeight,
    SprintSpeedMultiplier,
    SlideSpeed,
    SlideDuration,
    CrouchSpeed,
    Gravity,
    PistolDamage,
    PistolFireRate,
    PistolOverheatMax,
    PistolOverheatRegen,
    PistolRecoil,
    ShotgunDamage,
    ShotgunFirerate,
    ShotgunRecoil,
    ShotgunSpread,
    ShotgunBulletCount,
    ShotgunMag,
    SpeedWhileAiming,
    RegenRate,
    RegenStartDelay,
    GrenadeDamage,
    GrenadeRadius,
    GrenadeStickiness,
    GrenadeCount,
    GrenadeWeight,
    GrenadeDetonationSpeed,
    ShoveKnockback,
}
